services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: messagesdb
    ports:
      - "5432:5432"
    volumes:
      - /src/init.sql:/docker-entrypoint-initdb.d/init.sql
  

  api:
    build: 
      context: /src
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=messagesdb;Username=user;Password=password"
    ports:
      - "5000:80"
